#!/bin/bash

# note to self: in a script, BASH_SOURCE is an array with
# entry 0 = full file path to script
# entry 1 = full file path to pwd of script caller

alias greeting='clear; \echo -e "\n$(heading "$(date)")""\n"'
alias cyclelogin='\exec "$0" "$@" --init-file ~/.bash_profile'

alias rm='\rm -I --verbose'
alias hd='xxd -e -g4 -c32'
alias jobs='jobs -l; tasklist | grep agent'
alias hist='history | less +G'
function hash() {
    command hash "$@" | sort -r
}

if [[ "$OCTAVE_HOME" ]]
    then alias octave='"$OCTAVE_HOME"/mingw64/bin/octave-cli --interactive'; fi


declare -a grepargs=('--line-number' '--color=auto')
grepargs+=('--exclude-dir={.git,bin,build,dist,compile,db,incremental_db,node_modules,.vs,obj,packages,logs}')
if [[ -f "${XDG_CONFIG_HOME}/grep/excludefrom" ]]
    then grepargs+=('--exclude-from="${XDG_CONFIG_HOME}/grep/excludefrom"'); fi
alias fgrep='\grep '"${grepargs[@]}"''
alias  grep='\grep '"${grepargs[@]}"' --extended-regexp'
unset grepargs

function rgrep {
    grep -r --color=always "$@" | awk -F '[:]' -v OFS=':' 'f!=$1 {f=$1; print "\n"f} f==$1 {$1=""; printf "%34s",$2; $2=""; print}';
}


alias diff='\diff --side-by-side --suppress-common-lines --width="$COLUMNS" --color=auto'
#function manifest() {
#    local -ra choices="$(find -type f -name "*.jar")"
#    [[ "${#choices}" -le 0 ]] && return 1
#    select jarchoice in ${choices[@]}; do
#        [[ "$jarchoice" ]] && unzip -qc "$jarchoice" META-INF/MANIFEST.MF
#    done
#}


alias lag='lazygit'
alias gti='git'


function todo() {
    local -r todopath="${HOME}/.todo.md"
    "$EDITOR" "$todopath" -c 'vnew +set\ noma | wincmd p'
}


alias ls='\ls -CX --color=auto --group-directories-first'
function lsa() {
    ls "$@" -o --almost-all --human-readable
}
alias clsa='greeting; lsa'
function lsen() {
    for extension in "$@"; do
        echo
        lsa | \grep -Ei "\\S*[.]${extension}$" --
    done
}


# BOOKMARKED DIRECTORIES & DIRECTORY NAVIGATION:
alias root='\cd / && clsa'
function home() {
    clear
    stty -echo
    \echo -e "\n$(heading "$(date)")""\n"
    \cd "${HOME}" && ls --width=75 --hide=[nN][tT][uU][sS]*
    stty echo
}
alias config='\cd ${XDG_CONFIG_HOME} && clsa'


function numdirents() {
    local -a dirents=(*)
    local -i num="${#dirents}"
    dirents=(.*)
    num+="${#dirents}"
    echo -n "$((num-2))"
}


function yes() {
    [[ ! -t 1 ]] && exec \yes
    local -a colors=(red yellow green cyan blue magenta)
    local -i i=0
    while [[ i -lt "${#colors[@]}" ]]; do
        colors["$i"]="$(ansicode sgr start "${colors[$i]}")"
        i+=1
    done; i=0; readonly colors
    local payload="$@"
    readonly payload="${payload:=y\n}"
    trap 'echo -ne "\e[0m"; trap - SIGINT; return 0' SIGINT
    while : #sleep '0.01'
    do
        echo -ne "${colors[$i]}""$payload"
        let i="($i+1)"%"${#colors[@]}"
    done
}

function bind() {
    if [[ -z "$*" ]]; then
        local -r filterout="(self-insert)|(do-lowercase-version)"
        bind -p | grep -vT --color=always "$filterout" | less
    else
        command bind "$@"
    fi
}


# $1: string for heading text
function heading() {
    local payload="$1"
    [ "$payload" ] && payload=' '"$payload"' '
    local line=''
    local -ri payloadlen="${#payload}"
    printf -v line '%*s' "$((COLUMNS-payloadlen-3))"
    line="${line// /=}"
    echo -ne '==='"$payload"
    printf '%s\n' "$line"
}


# make functions unmodifiable:
readonly -f todo lsa lsen home numdirents yes heading
export   -f todo lsa lsen home numdirents yes heading

